### ISSUE TITLE
Build MyPaint.org Website

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/website#2]
Now that we have a basic tmp site up and running thanks to @achadwick, I just want to get a basic idea of what this site needs by compiling a list. After the is list locked down, I'll create separate issues for each check on the list and then work on each one at a time. This will help me keep on track and stay focus on what the site needs. It's how I approach things so bear with me. Here what I have so far.
- [x] Recover lost data from the Old Website. mypaint/website-old#3
- [x] Design the look of the Website. mypaint/website-theme#1 
- [x] Create Wiki for Future Contributors. mypaint/website#4
- [x] Add/Link Brush pack to the Downloads Page. mypaint/website-old#6
- [x] Create Features Page. mypaint/website#8

If you guys have an ideas for site please let me know down below and I'll probably add it to the list if it's needed. Alright lets get to it.

**Comment by AesaraB** [comment]
The scope of this issue is too broad.
